#include <day05/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day05.txt");
  const auto contents = util::Parse(fileName);

  auto seatIDs = util::day05::GetSeatIDs(contents);

  auto mySeatID = seatIDs.front();
  std::sort(seatIDs.begin(), seatIDs.end());
  for(auto it = seatIDs.begin(); it != seatIDs.end() - 1; it++)
  {
    if(*(it + 1) - *it > 1)
    {
      mySeatID = *it + 1;

      break;
    }
  }

  std::cout << mySeatID << "\n";

  return EXIT_SUCCESS;
}
