#include <day13/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto inputFile = util::GetInputFile("day13.txt");
  const auto contents = util::Parse(inputFile);

  const auto departureTime = util::day13::GetEarliestTimeToDepart(contents);
  auto buses = util::day13::GetBuses(contents, departureTime);
  const auto& firstBus = buses.front();

  util::day13::Time multiplier = 100000000000000;
  while(multiplier != 0)
  {
    const auto firstMultiple = firstBus.busId * multiplier;

    if(std::all_of(buses.begin(), buses.end(), [firstMultiple](const util::day13::Bus b) {
         return (firstMultiple + b.departureOffset) % b.busId == 0;
       }))
    {
      std::cout << firstMultiple << "\n";
      break;
    }

    ++multiplier;
  }

  return EXIT_SUCCESS;
}
