#include <day15/Utilities.ipp>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto inputFile = util::GetInputFile("day15.txt");
  const auto contents = util::Parse(inputFile);

  const auto nums = util::day15::GetStartingNumbers(contents);

  std::cout << util::day15::Get2020(nums) << "\n";

  return EXIT_SUCCESS;
}
