#include <day08/Utilities.ipp>

#include <algorithm>
#include <iomanip>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day08_sample.txt");
  const auto contents = util::Parse(fileName);

  std::cout << util::day08::GetFinalAccumulator(contents) << "\n";

  return EXIT_SUCCESS;
}
