#include <day07/Utilities.ipp>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day07.txt");
  const auto contents = util::Parse(fileName);

  const auto bags = util::day07::MakeBags(contents);
  const auto goldenBag = util::day07::StringToBag("shiny gold", bags);

  const auto requiredBags = util::day07::GetRequiredBagsWithin(goldenBag, bags);

  std::cout << requiredBags << "\n";

  return EXIT_SUCCESS;
}
