#include <day04/Utilities.ipp>

#include <iostream>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto inputFile = util::GetInputFile("day04.txt");
  const auto contents = util::Parse(inputFile);

  auto credentials = util::day04::GetCredentials(contents);
  const auto validCredentials =
      std::count_if(credentials.begin(), credentials.end(),
                    [](util::day04::Credential& x) { return x.isValid(); });

  std::cout << validCredentials << "\n";

  return EXIT_SUCCESS;
}
