#include <day06/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day06.txt");
  const auto contents = util::Parse(fileName);

  const auto groups = util::day06::GetGroups(contents);

  size_t unanimousAnswers = 0;
  for(const auto& group : groups)
  {
    std::vector<char> groupAnswers;
    for(const auto& person : group)
    {
      std::copy(person.begin(), person.end(), std::back_inserter(groupAnswers));
    }

    std::sort(groupAnswers.begin(), groupAnswers.end());
    groupAnswers.erase(std::unique(groupAnswers.begin(), groupAnswers.end()), groupAnswers.end());

    for(auto answer : groupAnswers)
    {
      if(std::all_of(group.begin(), group.end(), [answer](const std::string& x) {
           return x.find(answer) != std::string::npos;
         }))
      {
        ++unanimousAnswers;
      }
    }
  }

  std::cout << unanimousAnswers << "\n";

  return EXIT_SUCCESS;
}
