#include <day13/Utilities.ipp>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto inputFile = util::GetInputFile("day13.txt");
  const auto contents = util::Parse(inputFile);

  const auto departureTime = util::day13::GetEarliestTimeToDepart(contents);
  auto buses = util::day13::GetBuses(contents, departureTime);

  std::cout << util::day13::GetLowestTimeToWait(buses, departureTime) << "\n";

  return EXIT_SUCCESS;
}
