#include <day06/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day06.txt");
  const auto contents = util::Parse(fileName);

  const auto groups = util::day06::GetGroups(contents);

  size_t groupAnswerCounts = 0;
  for(const auto& group : groups)
  {
    std::vector<char> groupAnswers;
    for(const auto& line : group)
    {
      std::copy(line.begin(), line.end(), std::back_inserter(groupAnswers));
    }

    std::sort(groupAnswers.begin(), groupAnswers.end());
    groupAnswers.erase(std::unique(groupAnswers.begin(), groupAnswers.end()), groupAnswers.end());

    groupAnswerCounts += groupAnswers.size();
  }

  std::cout << groupAnswerCounts << "\n";

  return EXIT_SUCCESS;
}
