#include <day09/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day09.txt");
  const auto contents = util::Parse(fileName);

  std::vector<util::day09::NumberType> numbers;
  std::transform(
      contents.begin(), contents.end(), std::back_inserter(numbers),
      [](const std::string& x) { return util::StringTo<util::day09::NumberType>(x).value(); });

  constexpr size_t preambleLength = 25;
  std::optional<util::day09::NumberType> noSumOpt;
  for(size_t i = preambleLength; i < numbers.size() && !noSumOpt.has_value(); ++i)
  {
    auto preamble = util::day09::GetPreamble(numbers, preambleLength, i - preambleLength);
    auto number = numbers[i];

    if(!util::day09::GetCanFindSum(number, preamble))
    {
      noSumOpt = number;
    }
  }

  if(!noSumOpt.has_value())
  {
    std::cerr << "Could not find the sum for a number with input file '" << fileName
              << "' and preamble length " << preambleLength << "\n";
    return EXIT_FAILURE;
  }

  const auto contiguousSum = util::day09::GetContiguousSum(noSumOpt.value(), numbers);
  const auto [min, max] = std::minmax_element(contiguousSum.begin(), contiguousSum.end());
  if(min != contiguousSum.end() && max != contiguousSum.end())
  {
    std::cout << *min + *max << "\n";
  }
  else
  {
    std::cerr << "Could not find sum of min and max from contiguous range\n";
  }

  return EXIT_SUCCESS;
}
