#include <day10/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day10.txt");
  const auto contents = util::Parse(fileName);

  const auto joltages = util::day10::GetJoltages(contents);
  const auto deltas = util::day10::GetJoltageDeltas(joltages);
  const auto joltDiff1 =
      std::count_if(deltas.begin(), deltas.end(), [](size_t x) { return x == 1; });
  const auto joltDiff3 =
      std::count_if(deltas.begin(), deltas.end(), [](size_t x) { return x == 3; });

  std::cout << joltDiff1 * joltDiff3 << "\n";

  return EXIT_SUCCESS;
}
