#include <day12/Utilities.ipp>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day12.txt");
  const auto contents = util::Parse(fileName);

  const auto nis = util::day12::GetNavigationInstructions(contents);

  util::day12::Ship<util::day12::NavigationStrategy_Part2> s;
  for(const auto ni : nis)
  {
    s.doNavigationInstruction(ni);
  }

  std::cout << s.getManhattanDistance() << "\n";

  return EXIT_SUCCESS;
}
