#include <day08/Utilities.ipp>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day08.txt");
  const auto contents = util::Parse(fileName);

  std::vector<size_t> instructionsToInvert;
  for(size_t i = 0; i < contents.size(); ++i)
  {
    const auto instType = util::day08::StringToInstructionType(contents[i]);
    if(instType == util::day08::InstructionType::NOP ||
       instType == util::day08::InstructionType::JMP)
    {
      instructionsToInvert.push_back(i);
    }
  }

  for(auto index : instructionsToInvert)
  {
    auto copy = contents;
    copy[index] = util::day08::InvertInstruction(copy[index]);

    if(util::day08::GetDoesProgramTerminate(copy))
    {
      std::cout << util::day08::GetFinalAccumulator(copy) << "\n";
      break;
    }
  }

  return EXIT_SUCCESS;
}
