#include <day07/Utilities.ipp>

#include <algorithm>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto fileName = util::GetInputFile("day07.txt");
  const auto contents = util::Parse(fileName);

  const auto bags = util::day07::MakeBags(contents);

  const auto goldenBag = util::day07::Bag("shiny gold");
  const auto goldenBagCount =
      std::count_if(bags.begin(), bags.end(), [&](const util::day07::Bag& x) {
        return util::day07::GetCanHoldBag(x, goldenBag, bags);
      });

  std::cout << goldenBagCount << "\n";

  return EXIT_SUCCESS;
}
